# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "actions" , "refactoring-tests-controllers-and-models" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v20.x, 21.x, 22.x]
        mongodb-version: ['4.4']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'
        # cache: 'npm'
    - name: Install dependencies
      run: npm install
      working-directory: backend
    - run: npm run build --if-present
      working-directory: backend
    - run: npm test -- --coverage
      working-directory: backend
    - run: npm install
      working-directory: frontend
    - run: npm test -- --coverage
      working-directory: frontend
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: c4e18c22-d208-45b8-b6c3-7e683743cfa6
        slug: Collin-Cleary/NutritionTracker-CAZAM

  
          